### ISSUE TITLE
Добавить описание модуля

### ISSUE THREAD

**Issue by gromdron** [SerginhoLD/bitrix-favorites#1]
Скажите, а можно ли указать для чего этот модуль нужен и как он работает? Очень недостает информации

**Comment by SerginhoLD** [comment]
классный вопрос от интеграторов чего-то там, с более чем 200 проектами.
заголовок то вроде на русском языке.
в битриксе из коробки нет нормального решения хранить избранные элементы чего либо.
вот этот модуль предоставляет api для сохранения избранных элементов, ID товаров например.
это для программистов, а не для тыкальщиков/менеджеров/контентщиков.

**Comment by gromdron** [comment]
> классный вопрос от интеграторов чего-то там, с более чем 200 проектами.
> заголовок то вроде на русском языке.

О, нет-нет, если понадобится разберемся. Просто когда смотришь репозиторий в README не сразу понимаешь что это и для чего это нужно. 
Это как найти bitrix-cleaner и для того чтобы понять что именно он делает нужно лазить по исходному коду.
